[package]
name = "pingsix"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
env_logger = { version = "0.11.5", features = ["unstable-kv"] }
futures = "0.3.31"
hickory-resolver = "0.24.1"
http = "1.1.0"
log = { version = "0.4.22", features = ["kv"] }
matchit = "0.8.5"
once_cell = "1.20.2"
pingora = { version = "0.4", features = ["openssl"] }
pingora-core = "0.4.0"
pingora-error = "0.4.0"
pingora-http = "0.4.0"
pingora-load-balancing = "0.4.0"
pingora-proxy = "0.4.0"
regex = "1.11.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.34"
validator = { version = "0.18.1", features = ["derive"] }
