# pingora config example from https://github.com/cloudflare/pingora/blob/main/docs/user_guide/conf.md
pingora:
  version: 1
  threads: 2
  pid_file: /run/pingora.pid
  upgrade_sock: /tmp/pingora_upgrade.sock
  user: nobody
  group: webusers

# listener on TCP or TLS
listeners:
  - address: 0.0.0.0:8080
  # - address: "[::1]:443"
  #   tls:
  #     cert_path: /etc/ssl/server.crt
  #     key_path: /etc/ssl/server.key
  #   offer_h2: true

# api routers example for https://apisix.apache.org/docs/apisix/admin-api/#route
# Here is a complete example, which is a subset of routes from the apisix docs. The fields not mentioned here indicate that pingsix does not support them.
# The fields in the following comments are all optional parameters.
routers:
  - id: 1
    uri: /
    # uris: ["/","/test"]
    host: www.baidu.com
    # hosts: ["www.baidu.com","www.taobao.com"]
    # methods: ["GET", "POST"]
    # timeout:
    #   connect: 2
    #   send: 3
    #   read: 5
    # priority: 10
    upstream: # Field description https://apisix.apache.org/docs/apisix/admin-api/#upstream
      # id: 1
      # retries: 2
      # retry_timeout: 10
      nodes:
        "www.baidu.com": 1
      type: roundrobin # supported types: roundrobin, random, fnv, ketama
      # timeout:
      #   connect: 2
      #   send: 3
      #   read: 5
      checks: # Field description https://apisix.apache.org/docs/apisix/tutorials/health-check/
        active: # only support active check
          type: https
          timeout: 1
          host: www.baidu.com
          http_path: /
          # port: 8443
          https_verify_certificate: true
          req_headers: ["User-Agent: curl/7.29.0"]
          healthy:
            interval: 5
            http_statuses: [200, 201]
            successes: 2
          unhealthy:
            http_failures: 5
            tcp_failures: 2
      hash_on: vars # supported types: vars, cookie, header
      key: uri
      pass_host: rewrite
      upstream_host: www.baidu.com
      scheme: https
  - id: 2
    uri: /
    host: www.taobao.com
    upstream:
      nodes:
        "www.taobao.com": 1
      type: roundrobin
      pass_host: rewrite
      upstream_host: www.taobao.com
      scheme: http
