//! Gateway exit-response transformer, APISIX `exit-transformer` compatible.
//!
//! APISIX's plugin rewrites responses generated by the gateway itself (auth
//! failures, rate-limit rejections, upstream errors) through user-provided Lua
//! callbacks. PingSIX has no embedded scripting, so the same use cases —
//! status remapping and normalized error bodies — are expressed declaratively
//! as first-match-wins rules:
//!
//! ```json
//! "exit-transformer": {
//!   "rules": [
//!     {
//!       "codes": [401, 403],
//!       "status_code": 403,
//!       "body": "{\"error\":true,\"status\":$status,\"message\":\"$message\"}",
//!       "headers": {"Content-Type": "application/json", "X-Error-Code": "$status"}
//!     }
//!   ]
//! }
//! ```
//!
//! The plugin instance is a pure configuration carrier: it declares no phases,
//! so no per-request hooks run. Instead [`crate::utils::response::send_exit_response`]
//! looks the rules up through [`crate::core::ProxyPlugin::exit_transform`] at
//! every gateway exit (plugin short-circuits, `fail_to_proxy`, no-route 404),
//! which keeps a single choke point for error responses.

use std::sync::Arc;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use validator::Validate;

use crate::{
    core::{ExitTransform, ExitTransformRule, PluginPhases, ProxyError, ProxyPlugin, ProxyResult},
    plugins::config::parse_and_validate_plugin_config,
};

pub const PLUGIN_NAME: &str = "exit-transformer";

/// APISIX runs exit-transformer at priority 22950, before every plugin that
/// can generate an exit. PingSIX applies the rewrite in the shared exit
/// helper regardless of hook order; this value only keeps inventory order
/// aligned with APISIX.
const PRIORITY: i32 = 22950;

/// Creates an `exit-transformer` plugin instance from JSON configuration.
pub fn create_exit_transformer_plugin(
    cfg: JsonValue,
    _defaults: &crate::config::EffectiveDefaults,
) -> ProxyResult<Arc<dyn ProxyPlugin>> {
    let config = PluginConfig::try_from(cfg)?;
    Ok(Arc::new(PluginExitTransformer {
        compiled: config.compile(),
    }))
}

#[derive(Debug, Default, Serialize, Deserialize, Validate)]
struct PluginConfig {
    /// Ordered rewrite rules, evaluated first-match-wins.
    #[validate(length(min = 1))]
    #[validate(nested)]
    rules: Vec<RuleConfig>,
}

#[derive(Debug, Default, Serialize, Deserialize, Validate)]
struct RuleConfig {
    /// Gateway exit statuses this rule matches.
    #[validate(length(min = 1))]
    codes: Vec<u16>,
    /// Replacement status code; the matched status is kept when absent.
    #[validate(range(min = 100, max = 599))]
    status_code: Option<u16>,
    /// Replacement body; supports `$status`, `$message`, `$request_id`.
    body: Option<String>,
    /// Headers to add or override (`Content-Type` sets the body content type).
    #[serde(default)]
    headers: std::collections::BTreeMap<String, String>,
}

impl TryFrom<JsonValue> for PluginConfig {
    type Error = ProxyError;

    fn try_from(value: JsonValue) -> Result<Self, Self::Error> {
        let config: PluginConfig =
            parse_and_validate_plugin_config(value, "Invalid exit-transformer plugin config")?;
        for rule in &config.rules {
            for name in rule.headers.keys() {
                if name.eq_ignore_ascii_case("content-length") {
                    return Err(ProxyError::validation_error(
                        "exit-transformer must not set Content-Length; the gateway owns framing",
                    ));
                }
                if name.eq_ignore_ascii_case("transfer-encoding") {
                    return Err(ProxyError::validation_error(
                        "exit-transformer must not set Transfer-Encoding; the gateway owns framing",
                    ));
                }
            }
        }
        Ok(config)
    }
}

impl PluginConfig {
    fn compile(&self) -> ExitTransform {
        ExitTransform {
            rules: self
                .rules
                .iter()
                .map(|rule| ExitTransformRule {
                    codes: rule.codes.clone(),
                    status_code: rule.status_code,
                    body: rule.body.clone(),
                    headers: rule
                        .headers
                        .iter()
                        .map(|(k, v)| (k.clone(), v.clone()))
                        .collect(),
                })
                .collect(),
        }
    }
}

pub struct PluginExitTransformer {
    /// Rules precompiled at construction so request-time lookup is a borrow.
    compiled: ExitTransform,
}

#[async_trait]
impl ProxyPlugin for PluginExitTransformer {
    fn name(&self) -> &str {
        PLUGIN_NAME
    }

    fn priority(&self) -> i32 {
        PRIORITY
    }

    /// Deliberately empty: this plugin runs no per-request hooks. The shared
    /// exit-response helper reads its rules via [`Self::exit_transform`].
    fn phases(&self) -> PluginPhases {
        PluginPhases::empty()
    }

    fn exit_transform(&self) -> Option<&ExitTransform> {
        Some(&self.compiled)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn build(cfg: JsonValue) -> ExitTransform {
        PluginConfig::try_from(cfg).expect("valid config").compile()
    }

    #[test]
    fn config_requires_at_least_one_rule() {
        assert!(PluginConfig::try_from(serde_json::json!({ "rules": [] })).is_err());
        assert!(PluginConfig::try_from(serde_json::json!({})).is_err());
    }

    #[test]
    fn rule_requires_at_least_one_code() {
        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": []}]
        }))
        .is_err());
    }

    #[test]
    fn rule_rejects_out_of_range_status() {
        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": [404], "status_code": 99}]
        }))
        .is_err());
        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": [404], "status_code": 600}]
        }))
        .is_err());
        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": [404], "status_code": 403}]
        }))
        .is_ok());
    }

    #[test]
    fn unknown_fields_are_ignored_but_rules_still_required() {
        // APISIX configs carry Lua `functions`; porting requires `rules`, so a
        // `functions`-only config still fails on the missing `rules`.
        assert!(PluginConfig::try_from(serde_json::json!({
            "functions": ["return function() end"]
        }))
        .is_err());
        // Unknown fields next to valid rules are tolerated and ignored.
        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": [404]}],
            "functions": ["return function() end"]
        }))
        .is_ok());
    }

    #[test]
    fn framing_headers_are_rejected() {
        for headers in [
            serde_json::json!({ "Content-Length": "0" }),
            serde_json::json!({ "transfer-encoding": "chunked" }),
        ] {
            assert!(PluginConfig::try_from(serde_json::json!({
                "rules": [{"codes": [500], "headers": headers}]
            }))
            .is_err());
        }

        assert!(PluginConfig::try_from(serde_json::json!({
            "rules": [{"codes": [500], "headers": {"Retry-After": "30"}}]
        }))
        .is_ok());
    }

    #[test]
    fn compiled_rules_match_first_wins() {
        let transform = build(serde_json::json!({
            "rules": [
                {"codes": [401], "status_code": 403},
                {"codes": [401, 502], "status_code": 500}
            ]
        }));
        // 401 matches the first rule only.
        let matched = transform.matching(401).expect("rule matches");
        assert_eq!(matched.status_code, Some(403));
        // 502 falls through to the second rule.
        let matched = transform.matching(502).expect("rule matches");
        assert_eq!(matched.status_code, Some(500));
        assert!(transform.matching(404).is_none());
    }

    #[test]
    fn plugin_exposes_compiled_transform_and_no_phases() {
        let plugin = create_exit_transformer_plugin(
            serde_json::json!({
                "rules": [{"codes": [429], "headers": {"Retry-After": "30"}}]
            }),
            &crate::config::EffectiveDefaults::default(),
        )
        .expect("plugin builds");
        assert_eq!(plugin.name(), PLUGIN_NAME);
        assert_eq!(plugin.phases(), PluginPhases::empty());
        let transform = plugin.exit_transform().expect("rules exposed");
        let matched = transform.matching(429).expect("rule matches");
        assert_eq!(
            matched.headers,
            vec![("Retry-After".to_string(), "30".to_string())]
        );
    }
}
